name: MyFirstDemo-CI
on: [push]
jobs:
  MyFirstDemo-NG-Run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Angular Full CI
        # You may pin to the exact commit or the version.
        # uses: colbyhill21/angular-full-ci@a3489087f6a715db335078f999c01d422a254a6c
        uses: colbyhill21/angular-full-ci@v1.0
        #with:
          # Command to run tests on your project, do not prepend with "npm", it is already included.
          #testcommand: 
          # Set to true in order to run mocha tests. This option will install mocha on the image.
          #mocha: # optional
     
